apiVersion: v1
kind: Secret
metadata:
  name: "strapi-secrets"
type: Opaque
data:
  # generate 32 chars long random string, base64 encode it and then double-quote the result string.
  app-keys: {{ randAlphaNum 32 | b64enc | quote }}
  api-token-salt: {{ randAlphaNum 32 | b64enc | quote }}
  admin-jwt-secret: {{ randAlphaNum 32 | b64enc | quote }}
  jwt-secret: {{ randAlphaNum 32 | b64enc | quote }}